version: '3'

services:
  config-server:
    build: ./config-server
    ports:
     - "8888:8888"

  discovery-service:
    build: ./discovery-service
    ports:
     - "8082:8082"

  gateway-service:
    build: ./gateway-service
    ports:
     - "8080:8080"

  product-review-service:
    build: ./product-review-service
    ports:
     - "9091:9091"

  product-service:
    build: ./product-service
    ports:
     - "9090:9090"
