version: '3'

networks:
  challenge-network:
    driver: bridge

services:
  config-server:
    container_name: config-server
    image: config-server
    build: ./config-server
    ports:
      - "8888:8888"
    networks:
      - challenge-network

  discovery-service:
    container_name: discovery-service
    image: discovery-service
    build: ./discovery-service
    ports:
     - "8082:8082"
    depends_on:
      - config-server
    networks:
      - challenge-network
    links:
      - config-server:config-server

  gateway-service:
    container_name: gateway-service
    image: gateway-service
    build: ./gateway-service
    ports:
     - "8080:8080"
    depends_on:
      - discovery-service
    networks:
      - challenge-network
    links:
      - config-server:config-server

  product-review-service:
    container_name: product-review-service
    image: product-review-service
    build: ./product-review-service
    ports:
     - "9091:9091"
    depends_on:
      - gateway-service
    networks:
      - challenge-network
    links:
      - config-server:config-server
      - gateway-service:gateway-service
      - discovery-service:discovery-service

  product-service:
    container_name: product-service
    image: product-service
    build: ./product-service
    ports:
     - "9090:9090"
    depends_on:
      - gateway-service
    networks:
      - challenge-network
    links:
      - config-server:config-server
      - gateway-service:gateway-service
      - discovery-service:discovery-service
      - product-review-service:product-review-service
