
server:
  port: 9090
spring:
  jackson:
    default-property-inclusion: non_null
  application:
      name: product-service
external-resources:
  api:
    endpoint:
      product-review: http://localhost:9091/review
      product-details: https://www.adidas.co.uk/api/products

logging:
  level:
    org.springframework: error
    com.challenge.productservice: debug
    org.springframework.web: debug
management:
  endpoints:
    enabled-by-default: true
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    metrics:
      enabled: true