server:
  port: 9091
spring:
  h2:
    console:
      enabled: true
      path: /h2-review
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  jackson:
    default-property-inclusion: non_null